services:
  live-captions:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: live-captions-dev
    ports:
      - "8080:80"
    volumes:
      - ../src:/app/src:delegated
      - ../tsconfig.json:/app/tsconfig.json:delegated
      - ../scripts:/app/scripts:delegated
      # - ${SDK_PATH:-/dev/null}:/app/node_modules/@augmentos/sdk:delegated
      # Don't sync node_modules back to host
      - /app/node_modules
    environment:
      - PORT=80
      - NODE_ENV=development
    env_file:
      - ../.env
      - ../.env.development
    command: ["bun", "run", "dev"]
    restart: "no"
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - augmentos-network-dev

networks:
  augmentos-network-dev:
    external: true
    name: augmentos-network-dev